Name: Sourabh Kulkarni
Program: PhD
Reg. No.: 52-24-36

Q1.A Create a variable named var1 that stores an array of numbers from 0 to 30,
inclusive. Print var1 and its shape. Hint : arange

In [4]:
import numpy as np

var1 = np.arange(0,31) #generate numbers from 0 to 30 and store in an array
print (var1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]


Q1.B Change var2 to a validly-shaped two-dimensional matrix and store it in a
new variable called var2. Print var2 and its shape. Hint: Use the reshape function

In [ ]:
var2 = var1.reshape(31,1)
print(var2)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]]


Q1.C Create a third variable, var3 that reshapes it into a valid three-dimensional shape.
Print var3 and its shape.

In [ ]:
var3 = var2.reshape(31,1,1)
print(var3)

[[[ 0]]

 [[ 1]]

 [[ 2]]

 [[ 3]]

 [[ 4]]

 [[ 5]]

 [[ 6]]

 [[ 7]]

 [[ 8]]

 [[ 9]]

 [[10]]

 [[11]]

 [[12]]

 [[13]]

 [[14]]

 [[15]]

 [[16]]

 [[17]]

 [[18]]

 [[19]]

 [[20]]

 [[21]]

 [[22]]

 [[23]]

 [[24]]

 [[25]]

 [[26]]

 [[27]]

 [[28]]

 [[29]]

 [[30]]]


Q1.D Use two-dimensional array indexing to set the first value in the second row of var2
to -1. Now look at var1 and var3. Did they change? Explain what’s
going on. (Hint: does reshape return a view or a copy?)

In [ ]:
var2[1,0]=-1
print(var1)
print(var3)

[ 0 -1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
[[[ 0]]

 [[-1]]

 [[ 2]]

 [[ 3]]

 [[ 4]]

 [[ 5]]

 [[ 6]]

 [[ 7]]

 [[ 8]]

 [[ 9]]

 [[10]]

 [[11]]

 [[12]]

 [[13]]

 [[14]]

 [[15]]

 [[16]]

 [[17]]

 [[18]]

 [[19]]

 [[20]]

 [[21]]

 [[22]]

 [[23]]

 [[24]]

 [[25]]

 [[26]]

 [[27]]

 [[28]]

 [[29]]

 [[30]]]


Q1.E Another thing that comes up a lot with array shapes is thinking about how to
aggregate over specific dimensions. Figure out how the NumPy sum function
works (and the axis argument in particular) and do the following:
(i) Sum var3 over its second dimension and print the result.

In [10]:
np.sum(var3,axis=0)
print(var3)


[[[ 0]]

 [[-1]]

 [[ 2]]

 [[ 3]]

 [[ 4]]

 [[ 5]]

 [[ 6]]

 [[ 7]]

 [[ 8]]

 [[ 9]]

 [[10]]

 [[11]]

 [[12]]

 [[13]]

 [[14]]

 [[15]]

 [[16]]

 [[17]]

 [[18]]

 [[19]]

 [[20]]

 [[21]]

 [[22]]

 [[23]]

 [[24]]

 [[25]]

 [[26]]

 [[27]]

 [[28]]

 [[29]]

 [[30]]]


Q2.A The most basic kind of broadcast is with a scalar, in which you can perform a
binary operation (e.g., add, multiply, ...) on an array and a scalar, the effect is to
perform that operation with the scalar for every element of the array. To try this
out, create a vector 1, 2, . . . , 10 by adding 1 to the result of the arange function.

In [6]:
vector = np.arange(10) +1
print(vector)


[ 1  2  3  4  5  6  7  8  9 10]


Q2.B Now, create a 10 × 10 matrix A in which Ai j = i + j. You’ll be able to do this
using the vector you just created, and adding it to a reshaped version of itself.

In [11]:
varA = np.reshape(vector, (10, 1)) + vector
#print(vector)
print(varA)

[[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


Q2. C
A very common use of broadcasting is to standardize data, i.e., to make it have
zero mean and unit variance. First, create a fake “data set” with 50 examples,
each with five dimensions.
import numpy.random as npr
data = np.exp(npr.randn ( 50 , 5 ) )

In [12]:
import numpy.random as npr
data = np.exp(npr.randn ( 50 , 5 ) )
npr.randn()
print(data)


[[ 2.93940407  0.526826    0.76537276  0.32466966  4.66064732]
 [ 0.57246504  0.90732198  2.27520063  0.69871603  1.3862967 ]
 [ 0.76289971  1.46223411  3.92254913  0.47689072  0.36929669]
 [ 0.15123436  2.67732496  1.01746424  0.29413093  0.27633214]
 [ 0.91733126  5.52315423  5.30437734  1.67333046  3.97575844]
 [ 2.79500427  1.36453982  0.8105249   2.15519497  0.51677225]
 [ 0.22676678  0.4900093   2.965207    2.69906463  1.88964154]
 [ 1.86350865  1.39084804  1.47975192  3.10250903  1.23255359]
 [ 0.30817241  0.71005597  0.21513641  0.15004772  5.50003903]
 [ 1.64941104  0.90419887  2.40375839  2.3118469   6.98509937]
 [ 0.29974955  2.12058107  4.23757296  0.29505939  2.63722861]
 [ 2.16489058  2.87141317  1.59994678  0.38753793  0.42655268]
 [ 3.79633667  1.54668937  1.15718978  0.37286984  0.5173766 ]
 [ 0.35955522  0.70866432  0.40942978  0.95566029  0.26188311]
 [ 0.37228203  2.52691898  0.16081573  1.14785311  1.45009978]
 [ 1.46223922  2.67780879  0.19821088  1.29415695  0.25

Q2.D You don’t worry too much about what this code is doing at this stage of the
course, but for completeness: it imports the NumPy random number generation
library, then generates a 50 × 5 matrix of standard normal random variates and exponentiates them. The effect of this is to have a pretend
data set of 50 independent and identically-distributed vectors from a log-normal
distribution.

Q2.E Now, compute the mean and standard deviation of each column. This should
result in two vectors of length 5. You’ll need to think a little bit about how to use
the axis argument to mean and std. Store these vectors into variables and print
both of them.

In [14]:
col_mean = np.mean(data, axis=0)
col_std = np.std(data, axis=0)

print("Mean of each column:")
print(col_mean)

print("Standard deviation of each column:")
print(col_std)


Mean of each column:
[1.66273676 1.57196702 1.45646844 1.20489899 1.87855643]
Standard deviation of each column:
[2.05069459 1.39028112 1.27578042 0.9415856  2.30820934]


Q2.F Now standardize the data matrix by 1) subtracting the mean off of each column,
and 2) dividing each column by its standard deviation. Do this via broadcasting,
and store the result in a matrix called normalized. To verify that you successfully
did it, compute the mean and standard deviation of
the columns of normalized and print them out.

In [15]:
normalized = (data - col_mean) / col_std

normalized_col_mean = np.mean(normalized, axis=0)
normalized_col_std = np.std(normalized, axis=0)

print("Mean of each column of normalized data:")
print(normalized_col_mean)

print("Standard deviation of each column of normalized data:")
print(normalized_col_std)


Mean of each column of normalized data:
[ 1.19904087e-16 -5.77315973e-17  2.22044605e-17 -2.44249065e-16
 -1.06581410e-16]
Standard deviation of each column of normalized data:
[1. 1. 1. 1. 1.]


Q3.A A Vandermonde matrix is a matrix generated from a vector in which each column
of the matrix is an integer power starting from zero. So, if I have a column vector
[x1, x2, . . . , xN]
T
, then the associated (square) Vandermonde matrix would be

\\notag     V = \begin{bmatrix}                 1      &   1    & \dots & 1     \\                 x_1   & x_2   & \dots & x_n  \\                 \vdots &\vdots  &       & \vdots \\                 x_1^{n-1} & x_2^{n-1} & \dots & x_n^{n-1}    \end{bmatrix}        

Use what you learned about broadcasting in the previous problem to write a
function that will produce a Vandermonde matrix for a vector [1, 2, . . . ,N]T
for

any N. Do it without using a loop. Here’s a stub to get you started:
def vandermonde (N):
vec = np.arange (N) +1
# write your code here .
Use your function for N = 12, store it in variable named vander, and print the
result.

In [16]:
def vandermonde(N):
  vec = np.arange(N) + 1
  matrix = vec[:, np.newaxis] ** np.arange(N)
  return matrix
#Given : N = 12,
vander = vandermonde(12)
print(vander)


[[           1            1            1            1            1
             1            1            1            1            1
             1            1]
 [           1            2            4            8           16
            32           64          128          256          512
          1024         2048]
 [           1            3            9           27           81
           243          729         2187         6561        19683
         59049       177147]
 [           1            4           16           64          256
          1024         4096        16384        65536       262144
       1048576      4194304]
 [           1            5           25          125          625
          3125        15625        78125       390625      1953125
       9765625     48828125]
 [           1            6           36          216         1296
          7776        46656       279936      1679616     10077696
      60466176    362797056]
 [           1        

Q3.B Now, let’s make a pretend linear system problem with this matrix. Create a vector
of all ones, of length 12 and call it x. Perform a matrix-vector multiplication of
vander with the vector you just created and store that in a new vector and call it b.
Print the vector b.

In [17]:
x = np.ones(12)
b = np.dot(vander, x)
print(b)


[1.20000000e+01 4.09500000e+03 2.65720000e+05 5.59240500e+06
 6.10351560e+07 4.35356467e+08 2.30688120e+09 9.81706810e+09
 3.53036921e+10 1.11111111e+11 3.13842838e+11 8.10554586e+11]


Q3.C First, solve the linear system the naïve way, pretending like you don’t know x.
Import numpy.linalg, invert V and multiply it by b. Print out your result. What
should you get for your answer? If the answer is different than what you
expected, write a sentence about that difference.

In [19]:
import numpy.linalg as la

V_inv = la.inv(vander)
x_recovered = np.dot(V_inv, b)
print(x_recovered)

# ideal answer is vector of all 1s


[-12.26953125   5.90625     15.421875    -6.03515625   2.05859375
   0.92675781   1.00244141   1.00010681   0.99997711   1.00000131
   0.99999996   1.        ]


Q3.D Now, solve the same linear system using solve. Print out the result. Does it seem
more or less in line with what you’d expect?

In [20]:
x_recovered_solve = la.solve(vander, b)
print(x_recovered_solve)


[0.98080503 1.05139768 0.94513807 1.03151945 0.98899166 1.00248816
 0.99962407 1.0000384  0.99999737 1.00000012 1.         1.        ]


result usiung solve is more accurate